# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: Viren070
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          plugin_achievements: yes
          plugin_anilist: yes
          plugin_anilist_user: Viren070
          plugin_anilist_sections: watching, reading
          plugin_anilist_limit: 5
          plugin_anilist_shuffle: no
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_charts: yes
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_traffic: yes
